//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SickeCell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public long ClientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mi { get; set; }
        public string UniqueID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Age { get; set; }
        public string AgeGroup { get; set; }
        public string Ageat { get; set; }
        public string Gender { get; set; }
        public string Race { get; set; }
        public string Ethnicity { get; set; }
        public string SSSno { get; set; }
        public string CpNumber { get; set; }
        public string FullStreetAddress { get; set; }
        public string FullStreetAddress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string CountryCode { get; set; }
        public string CountyCodeDescription { get; set; }
        public string PhoneNumber { get; set; }
        public string Eligibility { get; set; }
        public string SickleCellDiagnosis { get; set; }
        public string PMPProviderName { get; set; }
        public string CCUCase { get; set; }
        public string Email_Address { get; set; }
        public string ClientresideinruralID { get; set; }
        public string Nameofmother { get; set; }
        public string Motheraddress { get; set; }
        public string Mothertel { get; set; }
        public string Nameoffather { get; set; }
        public string Fatheraddress { get; set; }
        public string Fathertel { get; set; }
        public string Nameofguardian { get; set; }
        public string Guardianaddress { get; set; }
        public string Guardiantel { get; set; }
        public string Emercont1 { get; set; }
        public string Emercont1homephone { get; set; }
        public string Emercont1cellphone { get; set; }
        public string Emercont2 { get; set; }
        public string Emercont2homephone { get; set; }
        public string Emercont2cellphone { get; set; }
        public string SicklecelltypeID { get; set; }
        public string HydroxyureaheardID { get; set; }
        public string HydroxyureatakenID { get; set; }
        public string HydroxyureacurrentlyID { get; set; }
        public string HydroxyureapasttakenID { get; set; }
        public string Comments { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string TimeStamp { get; set; }
        public Nullable<System.DateTime> Datenotescreated { get; set; }
    }
}
